In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("UCI_Credit_Card.csv")

In [6]:
df

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000.0,1,3,1,39,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,29997,150000.0,1,3,2,43,-1,-1,-1,-1,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,29998,30000.0,1,2,2,37,4,3,2,-1,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,29999,80000.0,1,3,1,41,1,-1,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,30000,50000.0,1,2,1,46,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [7]:
df = df.drop(labels=['ID'],axis=1)

In [8]:
df

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,20000.0,2,2,1,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,2,2,2,26,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,2,2,2,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,2,2,1,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,1,2,1,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,1,3,1,39,0,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,150000.0,1,3,2,43,-1,-1,-1,-1,0,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,30000.0,1,2,2,37,4,3,2,-1,0,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,80000.0,1,3,1,41,1,-1,0,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,50000.0,1,2,1,46,0,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [9]:
X = df.drop(labels=['default.payment.next.month'],axis=1)

In [10]:
X

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,20000.0,2,2,1,24,2,2,-1,-1,-2,...,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0
1,120000.0,2,2,2,26,-1,2,0,0,0,...,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0
2,90000.0,2,2,2,34,0,0,0,0,0,...,13559.0,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0
3,50000.0,2,2,1,37,0,0,0,0,0,...,49291.0,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0
4,50000.0,1,2,1,57,-1,0,-1,0,0,...,35835.0,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,1,3,1,39,0,0,0,0,0,...,208365.0,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0
29996,150000.0,1,3,2,43,-1,-1,-1,-1,0,...,3502.0,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0
29997,30000.0,1,2,2,37,4,3,2,-1,0,...,2758.0,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0
29998,80000.0,1,3,1,41,1,-1,0,0,0,...,76304.0,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0
29999,50000.0,1,2,1,46,0,0,0,0,0,...,49764.0,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0

In [11]:
y = df['default.payment.next.month']

In [12]:
y

0        1
1        1
2        0
3        0
4        0
        ..
29995    0
29996    0
29997    1
29998    1
29999    1
Name: default.payment.next.month, Length: 30000, dtype: int64

In [13]:
numerical_column =X.select_dtypes(exclude="object").columns

In [14]:
numerical_column

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6'],
      dtype='object')

In [15]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [16]:
num_pipeline = Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='median')),
        ('scalar',StandardScaler())
    ]
)

In [17]:
Preprocessor = ColumnTransformer(
    [
        ('num_pipeline',num_pipeline,numerical_column)
    ]
)

In [18]:
Preprocessor

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scalar', StandardScaler())]),
                                 Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6'],
      dtype='object'))])

In [19]:
#split data Train and Test
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.30,random_state=30)

In [22]:
Preprocessor.get_feature_names_out()

array(['num_pipeline__LIMIT_BAL', 'num_pipeline__SEX',
       'num_pipeline__EDUCATION', 'num_pipeline__MARRIAGE',
       'num_pipeline__AGE', 'num_pipeline__PAY_0', 'num_pipeline__PAY_2',
       'num_pipeline__PAY_3', 'num_pipeline__PAY_4',
       'num_pipeline__PAY_5', 'num_pipeline__PAY_6',
       'num_pipeline__BILL_AMT1', 'num_pipeline__BILL_AMT2',
       'num_pipeline__BILL_AMT3', 'num_pipeline__BILL_AMT4',
       'num_pipeline__BILL_AMT5', 'num_pipeline__BILL_AMT6',
       'num_pipeline__PAY_AMT1', 'num_pipeline__PAY_AMT2',
       'num_pipeline__PAY_AMT3', 'num_pipeline__PAY_AMT4',
       'num_pipeline__PAY_AMT5', 'num_pipeline__PAY_AMT6'], dtype=object)

In [23]:
X_train = pd.DataFrame(Preprocessor.fit_transform(X_train),columns=Preprocessor.get_feature_names_out())

ValueError: A given column is not a column of the dataframe

In [21]:
X_train

,num_pipeline__LIMIT_BAL,num_pipeline__SEX,num_pipeline__EDUCATION,num_pipeline__MARRIAGE,num_pipeline__AGE,num_pipeline__PAY_0,num_pipeline__PAY_2,num_pipeline__PAY_3,num_pipeline__PAY_4,num_pipeline__PAY_5,...,num_pipeline__BILL_AMT3,num_pipeline__BILL_AMT4,num_pipeline__BILL_AMT5,num_pipeline__BILL_AMT6,num_pipeline__PAY_AMT1,num_pipeline__PAY_AMT2,num_pipeline__PAY_AMT3,num_pipeline__PAY_AMT4,num_pipeline__PAY_AMT5,num_pipeline__PAY_AMT6
0,-1.139003,-1.231086,0.189892,0.855242,-1.031921,-0.872883,-0.720412,-0.694606,-0.665419,-1.532938,...,-0.667972,-0.683707,-0.669670,-0.629882,-0.259967,-0.219680,-0.284034,-0.262225,-0.169920,-0.289958
1,-0.138540,-1.231086,-1.076056,-1.060909,0.599775,0.901613,-1.558100,-0.694606,-0.665419,-0.647261,...,-0.651531,-0.586762,-0.662746,-0.652089,-0.333370,-0.166585,0.008592,-0.313948,-0.305063,-0.289958
2,0.631048,0.812291,-1.076056,0.855242,-0.705581,1.788862,1.792653,1.821359,1.910872,2.009769,...,1.124524,1.227215,1.416612,1.498716,0.010071,-0.060316,-0.284034,0.080871,-0.057618,-0.021965
3,1.477594,-1.231086,-1.076056,-1.060909,0.382216,0.901613,-1.558100,-1.533261,-1.524183,-0.647261,...,-0.674425,-0.671125,-0.651354,-0.533990,-0.333370,-0.237431,-0.284034,-0.268127,0.140338,-0.289958
4,0.861924,-1.231086,0.189892,-1.060909,0.926114,0.014365,0.117276,0.144049,0.193345,0.238416,...,1.080023,1.177725,1.212598,1.283075,0.121951,-0.059174,-0.055687,-0.028477,-0.038076,-0.067667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20995,-1.062045,0.812291,0.189892,-1.060909,0.273436,0.014365,0.117276,0.144049,0.193345,2.009769,...,-0.351942,-0.295819,-0.248487,-0.238640,-0.216949,-0.178393,-0.176273,-0.214481,-0.305063,-0.223321
20996,0.477130,0.812291,0.189892,-1.060909,-0.379242,-0.872883,0.117276,0.144049,0.193345,0.238416,...,-0.635504,-0.613340,-0.662746,-0.652089,-0.272482,-0.198072,-0.230154,-0.313948,-0.305063,2.195165
20997,0.708007,0.812291,0.189892,-1.060909,-0.379242,0.014365,0.117276,0.144049,0.193345,0.238416,...,0.790379,0.579140,0.691576,0.774827,-0.024855,-0.099675,-0.122392,-0.115013,-0.051273,-0.067834
20998,-0.908127,-1.231086,-1.076056,0.855242,0.273436,-0.872883,-0.720412,-0.694606,-0.665419,-0.647261,...,-0.668845,-0.665067,-0.656317,-0.567805,-0.310668,-0.222081,-0.263021,-0.288087,0.012809,-0.268301
20999,0.938883,0.812291,0.189892,-1.060909,1.905132,-0.872883,-0.720412,-0.694606,-0.665419,-0.647261,...,-0.653820,-0.655327,-0.600132,-0.569689,-0.321786,-0.180754,-0.229238,-0.062097,0.005703,-0.010415

In [24]:
X_test = pd.DataFrame(Preprocessor.fit_transform(X_test),columns=Preprocessor.get_feature_names_out())

In [25]:
X_test

,num_pipeline__LIMIT_BAL,num_pipeline__SEX,num_pipeline__EDUCATION,num_pipeline__MARRIAGE,num_pipeline__AGE,num_pipeline__PAY_0,num_pipeline__PAY_2,num_pipeline__PAY_3,num_pipeline__PAY_4,num_pipeline__PAY_5,...,num_pipeline__BILL_AMT3,num_pipeline__BILL_AMT4,num_pipeline__BILL_AMT5,num_pipeline__BILL_AMT6,num_pipeline__PAY_AMT1,num_pipeline__PAY_AMT2,num_pipeline__PAY_AMT3,num_pipeline__PAY_AMT4,num_pipeline__PAY_AMT5,num_pipeline__PAY_AMT6
0,-1.131446,-1.241923,0.176373,-1.048914,0.163489,0.016029,0.098944,0.126935,0.178178,1.977229,...,-0.525733,-0.500082,-0.483642,-0.524558,-0.217457,-0.256498,-0.287870,-0.297307,-0.308731,-0.243889
1,0.338197,0.805203,0.176373,0.866328,1.025977,0.912045,-1.560880,-1.529936,-1.516963,-1.523496,...,-0.686493,-0.675710,-0.663804,-0.654214,-0.367058,-0.348952,-0.337831,-0.297307,-0.339256,-0.301939
2,1.885189,-1.241923,-1.087447,0.866328,-0.914620,0.016029,-0.730968,-0.701500,0.178178,-0.648315,...,-0.456194,-0.044943,-0.371186,-0.081570,0.703711,0.641909,2.315544,0.762993,2.111135,-0.280518
3,0.338197,0.805203,-1.087447,0.866328,-0.698998,-1.776005,-1.560880,-1.529936,-1.516963,-1.523496,...,-0.686538,-0.675757,-0.653168,-0.623284,-0.367058,-0.348952,-0.337831,-0.258786,-0.207288,-0.220031
4,0.028798,0.805203,-1.087447,0.866328,0.379111,0.016029,0.098944,0.126935,0.178178,0.226866,...,-0.368323,-0.312823,-0.416165,-0.595246,-0.033583,-0.040772,0.093673,-0.051493,-0.088879,0.134653
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,0.415546,-1.241923,-1.087447,-1.048914,0.379111,0.016029,0.098944,0.126935,0.178178,0.226866,...,-0.504757,-0.603933,-0.603788,-0.667740,-0.232829,-0.164044,-0.271832,-0.297307,-0.339256,-0.127790
8996,1.266392,0.805203,-1.087447,-1.048914,0.379111,0.016029,0.098944,0.126935,0.178178,0.226866,...,0.020401,0.105821,0.186070,0.281434,-0.100863,-0.164044,-0.139833,-0.120335,0.015688,-0.185839
8997,-1.131446,-1.241923,0.176373,0.866328,-0.375565,0.016029,0.098944,0.126935,0.178178,0.226866,...,-0.459279,-0.503165,-0.478864,-0.474184,-0.253925,-0.257237,-0.260480,-0.274124,-0.309796,-0.266180
8998,-0.589999,0.805203,1.440193,0.866328,-1.345864,0.016029,0.098944,-0.701500,-0.669392,0.226866,...,-0.365737,-0.503881,-0.175628,-0.637729,1.629404,1.500129,0.390538,0.872834,-0.269261,0.952805
8999,0.879644,-1.241923,0.176373,0.866328,1.241599,0.016029,0.098944,0.126935,0.178178,0.226866,...,0.467265,0.306843,0.374610,0.416323,-0.100597,-0.132979,-0.126369,-0.161392,-0.161500,-0.168192

In [27]:
# Training model:
from sklearn.ensemble import RandomForestClassifier,VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import precision_score,recall_score,f1_score,accuracy_score

In [36]:
models = {
    'RF': RandomForestClassifier(),
    'DTC':DecisionTreeClassifier(),
    'logistic':LogisticRegression()
}
training_model_list = [],
models_list = [],
accuracy_score = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    print("Model training performance")
    model.fit(X_train,Y_train)

    #predict models
    y_pred = model.predict(X_test)

    print(list(models.values())[i])
    # models_list.append(list(models.keys())[i])

    print('Precision_score: ',precision_score(Y_test,y_pred))
    print('f1_score: ',f1_score(Y_test,y_pred))
    print('recall_score: ',recall_score(Y_test,y_pred))

    print("________________________________________")

Model training performance
RandomForestClassifier()
Precision_score:  0.6198723792160438
f1_score:  0.44840092317837127
recall_score:  0.3512396694214876
________________________________________
Model training performance
DecisionTreeClassifier()
Precision_score:  0.3502159403219474
f1_score:  0.39794780281061787
recall_score:  0.4607438016528926
________________________________________
Model training performance
LogisticRegression()
Precision_score:  0.6795580110497238
f1_score:  0.36992481203007516
recall_score:  0.25413223140495866
________________________________________